language: node_js
before_install:
  - npm i npm@4 -g --progress=false
  - npm i -g npm-install-peers coveralls --progress=false
before_script:
  - npm-install-peers
  - npm i react --progress=false || true
  - rm -rf node_modules/@types/node
after_success:
  - cat ./coverage/lcov.info | coveralls
node_js:
  - "9"